site_name: My Blog  # 网站标题
site_url: https://woodson-04.github.io/dlf.github.io/  # 替换为你的 GitHub Pages URL

theme:
  name: material
  features:
    - navigation.tab       # 标签式导航
    - navigation.indexes    # 自动生成目录
  palette:
    scheme: light           # 暗色主题
plugins:
  - search
  - gh-deploy:
      remote_branch: gh-pages  # 指定部署到 gh-pages 分支
nav:  # 导航菜单
  - Home: index.md
  - About: about.md
  - 文章:
    - 第一篇: posts/article1.md
    - 第二篇: posts/article2.md
